// Tests for `fab adapter validate` and the validateAdapter() library export.

import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

import { runFab, parseSingleEnvelope } from './__test-helpers__/cli-runner';
import { validateAdapter, AdapterValidateError } from './adapter-validate';
import { scaffoldAdapter, ADAPTER_TYPES, ADAPTER_INTERFACES } from './init';

function tmpDir(prefix: string): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), `fab-validate-${prefix}-`));
}
function tmpStateDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'fab-state-test-'));
}

describe('validateAdapter — library', () => {
  // Cross-ticket integration: every stub generated by #22's scaffoldAdapter
  // must validate cleanly. Catches the realistic regression where a stub
  // template loses a required method.
  it.each(ADAPTER_TYPES)('passes for scaffolded %s stub', (type) => {
    const dir = tmpDir(`scaffold-${type}`);
    try {
      const out = path.join(dir, 'Stub.ts');
      scaffoldAdapter(type, { out });
      const r = validateAdapter(out);
      expect(r.ok).toBe(true);
      expect(r.type).toBe(type);
      expect(r.errors).toEqual([]);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('reports missing methods', () => {
    const dir = tmpDir('missing');
    try {
      const file = path.join(dir, 'Bad.ts');
      // Missing: reset, validateEnvironment, verify, importRun
      fs.writeFileSync(file, `
        import type { AppAdapter, SeededEntity } from 'synthetic-test-fabric';
        export class BadAppAdapter implements AppAdapter {
          async seed(): Promise<SeededEntity[]> { return []; }
        }
      `);
      const r = validateAdapter(file);
      expect(r.ok).toBe(false);
      expect(r.type).toBe('app');
      expect(r.className).toBe('BadAppAdapter');
      const missing = r.errors.map((e) => e.method).sort();
      expect(missing).toEqual(['importRun', 'reset', 'validateEnvironment', 'verify']);
      for (const e of r.errors) {
        expect(e.kind).toBe('missing');
        expect(e.expected).toMatch(/^AppAdapter\./);
      }
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('auto-detects type from implements clause', () => {
    const dir = tmpDir('implements');
    try {
      const file = path.join(dir, 'a.ts');
      fs.writeFileSync(file, `
        import type { Reporter, FabricScore, FabricReport } from 'synthetic-test-fabric';
        export class WeirdName implements Reporter {
          async report(_s: FabricScore, _r: string): Promise<FabricReport> {
            return { format: 'console', content: '' };
          }
        }
      `);
      const r = validateAdapter(file);
      expect(r.type).toBe('reporter');
      expect(r.ok).toBe(true);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('auto-detects type from class-name suffix when no implements clause', () => {
    const dir = tmpDir('suffix');
    try {
      const file = path.join(dir, 'a.ts');
      fs.writeFileSync(file, `
        export class CustomScenarioPlanner {
          async plan(): Promise<unknown> { return {}; }
        }
      `);
      const r = validateAdapter(file);
      // Falls back to suffix → ScenarioPlanner → planner
      expect(r.type).toBe('planner');
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('respects --type override', () => {
    const dir = tmpDir('override');
    try {
      const file = path.join(dir, 'a.ts');
      // Class implements neither and has no recognizable suffix; explicit type forces it.
      fs.writeFileSync(file, `
        export class Whatever {
          async score(): Promise<unknown> { return {}; }
        }
      `);
      const r = validateAdapter(file, { type: 'scoring' });
      expect(r.ok).toBe(true);
      expect(r.type).toBe('scoring');
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('throws FILE_NOT_FOUND on missing path', () => {
    expect(() => validateAdapter('/tmp/nope-' + Date.now())).toThrow(AdapterValidateError);
    try { validateAdapter('/tmp/nope'); }
    catch (err) { expect((err as AdapterValidateError).code).toBe('FILE_NOT_FOUND'); }
  });

  it('throws NO_EXPORTED_CLASS when file has none', () => {
    const dir = tmpDir('no-class');
    try {
      const file = path.join(dir, 'a.ts');
      fs.writeFileSync(file, `export const x = 1;`);
      expect(() => validateAdapter(file)).toThrow(AdapterValidateError);
      try { validateAdapter(file); }
      catch (err) { expect((err as AdapterValidateError).code).toBe('NO_EXPORTED_CLASS'); }
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('throws AMBIGUOUS_TYPE when no clue about type', () => {
    const dir = tmpDir('ambig');
    try {
      const file = path.join(dir, 'a.ts');
      fs.writeFileSync(file, `export class Whatever {}`);
      expect(() => validateAdapter(file)).toThrow(AdapterValidateError);
      try { validateAdapter(file); }
      catch (err) { expect((err as AdapterValidateError).code).toBe('AMBIGUOUS_TYPE'); }
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});

describe('fab adapter validate — CLI', () => {
  it('emits success envelope (status:ok, data.ok:true) on a valid stub', async () => {
    const dir = tmpDir('cli-pass');
    const stateDir = tmpStateDir();
    try {
      const out = path.join(dir, 'a.ts');
      scaffoldAdapter('app', { out });
      const r = await runFab(['adapter', 'validate', out, '--json'], { env: { FAB_STATE_DIR: stateDir } });
      expect(r.exitCode).toBe(0);
      const env: any = parseSingleEnvelope(r.stdout);
      expect(env.status).toBe('ok');
      expect(env.data.ok).toBe(true);
      expect(env.data.type).toBe('app');
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
      fs.rmSync(stateDir, { recursive: true, force: true });
    }
  });

  it('emits domain-failure envelope (status:ok, data.ok:false, exit 1) on missing methods', async () => {
    const dir = tmpDir('cli-fail');
    const stateDir = tmpStateDir();
    try {
      const file = path.join(dir, 'a.ts');
      fs.writeFileSync(file, `
        import type { AppAdapter } from 'synthetic-test-fabric';
        export class IncompleteAppAdapter implements AppAdapter {}
      `);
      const r = await runFab(['adapter', 'validate', file, '--json'], { env: { FAB_STATE_DIR: stateDir } });
      // Per #18 outcome taxonomy: tool ran, found problems → status:ok + data.ok:false.
      expect(r.exitCode).toBe(1);
      const env: any = parseSingleEnvelope(r.stdout);
      expect(env.status).toBe('ok');
      expect(env.data.ok).toBe(false);
      expect(env.data.errors.length).toBe(5); // app interface has 5 methods
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
      fs.rmSync(stateDir, { recursive: true, force: true });
    }
  });

  it('emits FILE_NOT_FOUND infrastructure error', async () => {
    const stateDir = tmpStateDir();
    try {
      const r = await runFab(['adapter', 'validate', '/tmp/does-not-exist-' + Date.now(), '--json'], { env: { FAB_STATE_DIR: stateDir } });
      expect(r.exitCode).toBe(1);
      const env: any = parseSingleEnvelope(r.stdout);
      expect(env.status).toBe('error');
      expect(env.error.code).toBe('FILE_NOT_FOUND');
    } finally {
      fs.rmSync(stateDir, { recursive: true, force: true });
    }
  });

  it('--type override works', async () => {
    const dir = tmpDir('cli-type');
    const stateDir = tmpStateDir();
    try {
      const file = path.join(dir, 'a.ts');
      fs.writeFileSync(file, `export class Whatever { async score() { return {}; } }`);
      const r = await runFab(['adapter', 'validate', file, '--type', 'scoring', '--json'], { env: { FAB_STATE_DIR: stateDir } });
      expect(r.exitCode).toBe(0);
      const env: any = parseSingleEnvelope(r.stdout);
      expect(env.data.type).toBe('scoring');
      expect(env.data.ok).toBe(true);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
      fs.rmSync(stateDir, { recursive: true, force: true });
    }
  });
});

describe('validateAdapter — review-flagged regressions', () => {
  // Reviewer finding 1: validateAdapter() ignored TypeScript parse diagnostics,
  // so malformed TS could validate as ok:true.
  it('throws SYNTAX_ERROR on malformed TypeScript', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fab-validate-syntax-'));
    try {
      const file = path.join(dir, 'Bad.ts');
      fs.writeFileSync(file, `
        import type { ScoringAdapter } from 'synthetic-test-fabric';
        export class BrokenScoringAdapter implements ScoringAdapter {
          score(:::): {
      `);
      expect(() => validateAdapter(file)).toThrow(AdapterValidateError);
      try { validateAdapter(file); }
      catch (err) {
        expect((err as AdapterValidateError).code).toBe('SYNTAX_ERROR');
        expect((err as AdapterValidateError).message).toMatch(/parse error at line/);
      }
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  // Reviewer finding 2: method scan only counted MethodDeclaration, so valid
  // class-field arrow implementations were falsely reported missing.
  it('accepts class-field arrow implementations', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fab-validate-arrow-'));
    try {
      const file = path.join(dir, 'Arrow.ts');
      fs.writeFileSync(file, `
        import type { ScoringAdapter, FabricScore } from 'synthetic-test-fabric';
        export class ArrowScoringAdapter implements ScoringAdapter {
          score = async (_iterRoot: string): Promise<FabricScore> => ({} as FabricScore);
        }
      `);
      const r = validateAdapter(file);
      expect(r.ok).toBe(true);
      expect(r.errors).toEqual([]);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  it('accepts class-field function-expression implementations', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fab-validate-fnexpr-'));
    try {
      const file = path.join(dir, 'FnExpr.ts');
      fs.writeFileSync(file, `
        import type { Reporter } from 'synthetic-test-fabric';
        export class FnExprReporter implements Reporter {
          report = async function(_score: any, _root: any) {
            return { format: 'console' as const, content: '' };
          };
        }
      `);
      expect(validateAdapter(file).ok).toBe(true);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  it('still reports missing when arrow field is named differently', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fab-validate-arrow-miss-'));
    try {
      const file = path.join(dir, 'WrongName.ts');
      fs.writeFileSync(file, `
        import type { ScoringAdapter } from 'synthetic-test-fabric';
        export class WrongNameScoringAdapter implements ScoringAdapter {
          computeScore = async (_root: string) => ({} as any);
        }
      `);
      const r = validateAdapter(file);
      expect(r.ok).toBe(false);
      expect(r.errors[0].method).toBe('score');
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  it('still reports missing when class field is non-callable', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fab-validate-noncallable-'));
    try {
      const file = path.join(dir, 'NonCallable.ts');
      fs.writeFileSync(file, `
        import type { ScoringAdapter } from 'synthetic-test-fabric';
        export class NonCallableScoringAdapter implements ScoringAdapter {
          score = 42;
        }
      `);
      const r = validateAdapter(file);
      expect(r.ok).toBe(false);
      expect(r.errors[0].method).toBe('score');
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });
});

describe('cross-check: every interface in ADAPTER_INTERFACES is in INTERFACE_METHODS', () => {
  // Catches regressions where a new adapter type is added but the
  // INTERFACE_METHODS table isn't updated.
  it.each(ADAPTER_TYPES)('%s has expected methods registered', (type) => {
    const ifaceName = ADAPTER_INTERFACES[type];
    expect(ifaceName).toBeDefined();
    // Validating a scaffolded stub of this type proves the lookup works.
    const dir = tmpDir(`xcheck-${type}`);
    try {
      const out = path.join(dir, 'a.ts');
      scaffoldAdapter(type, { out });
      const r = validateAdapter(out);
      expect(r.ok).toBe(true);
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });
});
