/**
 * `fab init` — scaffolds a parseable `fabric.config.ts` plus stub adapters
 * into the target directory. The generated config is shaped to load
 * immediately via `loadFabricConfig()` so `fab doctor` (#24) and other
 * commands don't blow up the moment the user runs `fab init`.
 *
 * Adapter stubs follow the real interface names exported from the package:
 * `AppAdapter`, `SimulationAdapter`, `ScoringAdapter`, `FeedbackAdapter`,
 * `MemoryAdapter`, `BrowserAdapter`, `Reporter`, `ScenarioPlanner`. Each
 * stub returns a no-op for methods the framework allows to be empty
 * (e.g., `reset`, `clean`, `validateEnvironment`) and throws
 * `new Error('TODO: implement <method>')` for required methods so
 * unimplemented adapters fail loudly rather than silently no-op.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface InitOptions {
  /** Target directory for scaffolding (defaults to process.cwd()). */
  dir?: string;
  /** Overwrite existing files instead of failing. */
  force?: boolean;
  /** Package name to import from in generated stubs. Default 'synthetic-test-fabric'. */
  packageName?: string;
}

export interface InitResult {
  filesCreated: string[];
  filesSkipped: string[];     // files that already existed (only populated when not --force)
}

export class InitConflictError extends Error {
  readonly code = 'INIT_CONFLICT';
  readonly conflicts: string[];
  constructor(conflicts: string[]) {
    super(`fab init: ${conflicts.length} file(s) already exist; pass --force to overwrite`);
    this.name = 'InitConflictError';
    this.conflicts = conflicts;
  }
}

interface FileSpec {
  /** Relative path from the target dir. */
  relPath: string;
  /** File body. */
  content: string;
}

export function scaffoldProject(opts: InitOptions = {}): InitResult {
  const targetDir = path.resolve(opts.dir ?? process.cwd());
  const pkg = opts.packageName ?? 'synthetic-test-fabric';

  const files = generateFileSpecs(pkg);

  // Check for conflicts before writing anything.
  const conflicts = files
    .map((f) => path.join(targetDir, f.relPath))
    .filter((p) => fs.existsSync(p));
  if (conflicts.length > 0 && !opts.force) {
    throw new InitConflictError(conflicts);
  }

  // Write all files (atomic-ish: errors mid-batch leave partial state, but
  // that's no worse than the conflict-check pattern).
  const filesCreated: string[] = [];
  for (const f of files) {
    const full = path.join(targetDir, f.relPath);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, f.content);
    filesCreated.push(full);
  }

  return { filesCreated, filesSkipped: [] };
}

// ---------------------------------------------------------------------------
// Template generation
// ---------------------------------------------------------------------------

function generateFileSpecs(pkg: string): FileSpec[] {
  return [
    { relPath: 'fabric.config.ts',                    content: fabricConfigTemplate(pkg) },
    { relPath: 'src/adapters/MyAppAdapter.ts',        content: appAdapterStub(pkg) },
    { relPath: 'src/adapters/MySimulationAdapter.ts', content: simulationAdapterStub(pkg) },
    { relPath: 'src/adapters/MyScoringAdapter.ts',    content: scoringAdapterStub(pkg) },
    { relPath: 'src/adapters/MyFeedbackAdapter.ts',   content: feedbackAdapterStub(pkg) },
    { relPath: 'src/adapters/MyMemoryAdapter.ts',     content: memoryAdapterStub(pkg) },
    { relPath: 'src/adapters/MyBrowserAdapter.ts',    content: browserAdapterStub(pkg) },
    { relPath: 'src/adapters/MyReporter.ts',          content: reporterStub(pkg) },
    { relPath: 'src/adapters/MyScenarioPlanner.ts',   content: scenarioPlannerStub(pkg) },
    { relPath: 'flows/.gitkeep',                      content: '' },
  ];
}

const TODO = (method: string) => `throw new Error('TODO: implement ${method}');`;

function fabricConfigTemplate(pkg: string): string {
  return `// Generated by \`fab init\`. Wire your real adapters in src/adapters/ and customize this file.
import type { FabricConfig } from '${pkg}';
import { MyAppAdapter } from './src/adapters/MyAppAdapter';
import { MySimulationAdapter } from './src/adapters/MySimulationAdapter';
import { MyScoringAdapter } from './src/adapters/MyScoringAdapter';
import { MyFeedbackAdapter } from './src/adapters/MyFeedbackAdapter';
import { MyMemoryAdapter } from './src/adapters/MyMemoryAdapter';
import { MyBrowserAdapter } from './src/adapters/MyBrowserAdapter';
import { MyReporter } from './src/adapters/MyReporter';
import { MyScenarioPlanner } from './src/adapters/MyScenarioPlanner';

const config: FabricConfig = {
  adapters: {
    app:        new MyAppAdapter(),
    simulation: new MySimulationAdapter(),
    scoring:    new MyScoringAdapter(),
    feedback:   new MyFeedbackAdapter(),
    memory:     new MyMemoryAdapter(),
    browser:    new MyBrowserAdapter(),
    reporters:  [new MyReporter()],
    planner:    new MyScenarioPlanner(),
  },
};

export default config;
`;
}

function appAdapterStub(pkg: string): string {
  return `import type { AppAdapter, SeededEntity, AppHealthResult } from '${pkg}';

export class MyAppAdapter implements AppAdapter {
  async seed(_iterRoot: string, _config: { seekers: number; employers: number; employees: number; scenarioName?: string; personaAdjustmentsPath?: string }): Promise<SeededEntity[]> {
    ${TODO('MyAppAdapter.seed')}
  }

  async reset(_iterRoot: string): Promise<void> {
    // No-op is acceptable here; remove app state created by seed() if your
    // app keeps long-lived data between iterations.
  }

  async validateEnvironment(): Promise<AppHealthResult> {
    return { healthy: true, errors: [], warnings: [] };
  }

  async verify(_iterRoot: string): Promise<void> {
    ${TODO('MyAppAdapter.verify')}
  }

  async importRun(_iterRoot: string, _dbUrl: string): Promise<void> {
    // No-op is acceptable; only called when dbUrl is provided.
  }
}
`;
}

function simulationAdapterStub(pkg: string): string {
  return `import type { SimulationAdapter, SeededEntity, SimulationRunResult } from '${pkg}';

export class MySimulationAdapter implements SimulationAdapter {
  async run(_iterRoot: string, _options: { ticks: number; liveLlm: boolean; simulationId?: string }): Promise<SimulationRunResult> {
    ${TODO('MySimulationAdapter.run')}
  }

  async exportEntities(_iterRoot: string, _entities: SeededEntity[]): Promise<void> {
    ${TODO('MySimulationAdapter.exportEntities')}
  }

  async clean(_iterRoot: string): Promise<void> {
    // No-op is acceptable.
  }
}
`;
}

function scoringAdapterStub(pkg: string): string {
  return `import type { ScoringAdapter, FabricScore } from '${pkg}';

export class MyScoringAdapter implements ScoringAdapter {
  async score(_iterRoot: string): Promise<FabricScore> {
    ${TODO('MyScoringAdapter.score')}
  }
}
`;
}

function feedbackAdapterStub(pkg: string): string {
  return `import type { FeedbackAdapter, FabricFeedback, FabricScore } from '${pkg}';

export class MyFeedbackAdapter implements FeedbackAdapter {
  async feedback(_iterRoot: string, _options: { score: FabricScore; loopId: string; iteration: number; previousIterRoot: string | null }): Promise<FabricFeedback> {
    ${TODO('MyFeedbackAdapter.feedback')}
  }
}
`;
}

function memoryAdapterStub(pkg: string): string {
  return `import type { MemoryAdapter, RecorderInput, SeededEntity } from '${pkg}';

export class MyMemoryAdapter implements MemoryAdapter {
  migrate(_dbPath: string): void {
    ${TODO('MyMemoryAdapter.migrate')}
  }

  writeEvent(_dbPath: string, _event: RecorderInput): void {
    ${TODO('MyMemoryAdapter.writeEvent')}
  }

  resolveEntity(_dbPath: string, _alias: string): SeededEntity | null {
    return null;
  }

  listEntities(_dbPath: string, _simulationId: string): SeededEntity[] {
    return [];
  }
}
`;
}

function browserAdapterStub(pkg: string): string {
  return `import type { BrowserAdapter, BrowserRunResult, LlmProvider } from '${pkg}';

export class MyBrowserAdapter implements BrowserAdapter {
  async runSpecs(_options: {
    iterRoot: string;
    project: string;
    allowFailures: boolean;
    grep?: string;
    retryCount?: number;
    retryDelayMs?: number;
    quarantinedFlows?: string[];
    llmProvider?: LlmProvider;
  }): Promise<BrowserRunResult> {
    ${TODO('MyBrowserAdapter.runSpecs')}
  }
}
`;
}

function reporterStub(pkg: string): string {
  return `import type { Reporter, FabricScore, FabricReport } from '${pkg}';

export class MyReporter implements Reporter {
  async report(_score: FabricScore, _iterRoot: string): Promise<FabricReport> {
    return { format: 'console', content: '(stub reporter — replace with real implementation)' };
  }
}
`;
}

function scenarioPlannerStub(pkg: string): string {
  return `import type { ScenarioPlanner, FabricScore, ScenarioPlan } from '${pkg}';

export class MyScenarioPlanner implements ScenarioPlanner {
  async plan(_score: FabricScore, _iterRoot: string): Promise<ScenarioPlan> {
    return {
      scenarioName: 'baseline_browser_flow',
      rationale: 'stub planner — always returns baseline; replace with your selection logic',
      personaAdjustments: [],
    };
  }
}
`;
}
