import * as fs from 'fs';
import * as path from 'path';
import { execSync, spawn } from 'child_process';
import { randomUUID } from 'crypto';
import BetterSqlite3 from 'better-sqlite3';
import {
  AppAdapter,
  SimulationAdapter,
  ScoringAdapter,
  FeedbackAdapter,
  MemoryAdapter,
  BrowserAdapter,
  Reporter,
  ScenarioPlanner,
  applyLisaDbMigrations,
  BehaviorEventRecorder,
  BEHAVIOR_OUTCOMES,
  parsePlaywrightResults,
} from '../dist/index.js';
import type {
  AppHealthResult,
  SeededEntity,
  SimulationRunResult,
  BrowserRunResult,
  FabricScore,
  FabricFeedback,
  FabricReport,
  ScenarioPlan,
  RecorderInput,
  PersonaAdjustment,
} from '../dist/index.js';

interface LisaMcpModule {
  buildLisaMcpCommand(): { cmd: string; args: string[] };
  verifyBinary(): Promise<{ ok: boolean; version?: string; error?: string }>;
}

// ---------------------------------------------------------------------------
// Known data-key map for the Taskboard SPA (used as fallback / spec template)
// ---------------------------------------------------------------------------
const DATA_KEY_MAP = {
  home:     ['home.title', 'home.description', 'home.get_started_btn'],
  login:    ['login.title', 'login.email_input', 'login.password_input', 'login.submit_btn', 'login.error_msg'],
  dashboard:['dashboard.title', 'dashboard.task_list', 'dashboard.task_title_input',
             'dashboard.create_task_btn', 'dashboard.new_task_btn', 'dashboard.validation_error'],
  task:     ['task.title_heading', 'task.complete_btn', 'task.reopen_btn', 'task.back_btn',
             'task.status_value', 'task.description'],
  profile:  ['profile.title', 'profile.name_label', 'profile.role_badge',
             'profile.stat_total', 'profile.stat_done', 'profile.stat_pct', 'profile.logout_btn'],
};

// ---------------------------------------------------------------------------
// AppAdapter
// ---------------------------------------------------------------------------
export class DemoAppAdapter implements AppAdapter {
  async seed(iterRoot: string, config: { seekers: number; employers: number; employees: number }): Promise<SeededEntity[]> {
    const lisaDir = path.join(iterRoot, '.lisa_memory');
    fs.mkdirSync(lisaDir, { recursive: true });

    const dbPath = path.join(lisaDir, 'lisa.db');
    const db = new BetterSqlite3(dbPath);
    applyLisaDbMigrations(db);

    const entities: SeededEntity[] = [];

    for (let i = 1; i <= config.seekers; i++) {
      db.prepare(`INSERT OR IGNORE INTO seeded_entities (entity_type, entity_id, auth_email, auth_password, data)
                  VALUES (?, ?, ?, ?, ?)`).run(
        'demo_user', `user-${i}`, `user${i}@demo.test`, 'demo123',
        JSON.stringify({ name: `Demo User ${i}`, role: 'member' }),
      );
      entities.push({
        alias: `seeker-${i}`,
        id: `user-${i}`,
        type: 'demo_user',
        credentials: { email: `user${i}@demo.test`, password: 'demo123' },
      });
    }

    for (let i = 1; i <= config.employers; i++) {
      db.prepare(`INSERT OR IGNORE INTO seeded_entities (entity_type, entity_id, auth_email, auth_password, data)
                  VALUES (?, ?, ?, ?, ?)`).run(
        'demo_user', `emp-${i}`, `employer${i}@demo.test`, 'demo123',
        JSON.stringify({ name: `Employer ${i}`, role: 'employer' }),
      );
      entities.push({
        alias: `employer-${i}`,
        id: `emp-${i}`,
        type: 'demo_user',
        credentials: { email: `employer${i}@demo.test`, password: 'demo123' },
      });
    }

    db.close();

    fs.writeFileSync(
      path.join(iterRoot, 'mini-sim-export.json'),
      JSON.stringify({ entities, seededAt: new Date().toISOString() }, null, 2),
    );

    // Write seed-data.js so the SPA can bootstrap user list from seeded entities
    const seedUsers = entities.map(e => ({
      id: e.id,
      email: e.credentials!.email,
      password: e.credentials!.password,
      name: `Demo User ${e.id}`,   // overwritten per-entity below
      role: e.alias.startsWith('employer') ? 'employer' : 'member',
    }));
    // Resolve real names from the DB we just wrote
    const nameDb = new BetterSqlite3(dbPath);
    for (const u of seedUsers) {
      const row = nameDb.prepare('SELECT data FROM seeded_entities WHERE entity_id = ?').get(u.id) as any;
      if (row?.data) {
        try {
          u.name = JSON.parse(row.data).name ?? u.name;
        } catch {
          continue;
        }
      }
    }
    nameDb.close();
    const seedDataJs = `// AUTO-GENERATED by DemoAppAdapter.seed() — do not edit manually\nwindow.__DEMO_SEED__ = ${JSON.stringify({ users: seedUsers }, null, 2)};\n`;
    fs.writeFileSync(path.join(__dirname, 'app', 'seed-data.js'), seedDataJs, 'utf8');

    return entities;
  }

  async reset(_iterRoot: string): Promise<void> {}

  async validateEnvironment(): Promise<AppHealthResult> {
    return { healthy: true, errors: [], warnings: [] };
  }

  async verify(iterRoot: string): Promise<void> {
    const exportPath = path.join(iterRoot, 'mini-sim-export.json');
    if (!fs.existsSync(exportPath)) {
      throw new Error(`[demo] verify: mini-sim-export.json not found at ${exportPath}`);
    }
    const { entities } = JSON.parse(fs.readFileSync(exportPath, 'utf8'));
    if (!entities?.length) throw new Error('[demo] verify: no seeded entities — fail closed');
    console.log(`[demo] verify: ${entities.length} entities confirmed`);
  }

  async importRun(_iterRoot: string, _dbUrl: string): Promise<void> {}
}

// ---------------------------------------------------------------------------
// SimulationAdapter — real behavior events + candidate flow extraction
// ---------------------------------------------------------------------------
export class DemoSimulationAdapter implements SimulationAdapter {
  async run(iterRoot: string, options: { ticks: number; liveLlm: boolean }): Promise<SimulationRunResult> {
    const simulationId = `demo-sim-${Date.now()}`;
    const dbPath = path.join(iterRoot, '.lisa_memory', 'lisa.db');

    BehaviorEventRecorder.reset();
    const recorder = BehaviorEventRecorder.getInstance(dbPath, 'simulation');
    const now = () => new Date().toISOString();

    // Each discrete agent action gets its own unique execution_id so the recorder's
    // (execution_id, execution_state) idempotency index never silently drops events.
    const ev = (
      agent_id: string, entity_id: string, persona: string, t: number,
      action: string, reasoning: string,
      outcome: RecorderInput['outcome'], outcome_detail: string | null,
      screen_path: string, entity_refs: string | null,
    ): RecorderInput => ({
      simulation_id: simulationId,
      execution_id: randomUUID(),     // unique per action — no idempotency dedup
      agent_id, entity_id, persona_definition_id: persona, tick: t,
      sim_time: now(), action, reasoning,
      event_source: 'agent', event_kind: 'action', execution_state: 'completed',
      outcome, outcome_detail, screen_path, entity_refs,
    });

    // Simulate each tick
    for (let tick = 1; tick <= options.ticks; tick++) {
      // ── seeker-1: login → dashboard → create task → view task ──────────────
      recorder.record(ev('seeker-agent-1', 'user-1', 'casual_member', tick,
        'navigate_to_login', 'Starting session — need to authenticate',
        BEHAVIOR_OUTCOMES.SUCCESS, null, 'auth/login', null));
      recorder.record(ev('seeker-agent-1', 'user-1', 'casual_member', tick,
        'fill_login_credentials', 'Entering email user1@demo.test and password',
        BEHAVIOR_OUTCOMES.SUCCESS, null, 'auth/login',
        JSON.stringify({ user_id: 'user-1' })));
      recorder.record(ev('seeker-agent-1', 'user-1', 'casual_member', tick,
        'submit_login_form', 'Credentials entered — submitting',
        BEHAVIOR_OUTCOMES.SUCCESS, 'Redirected to dashboard', 'auth/login',
        JSON.stringify({ user_id: 'user-1' })));
      recorder.record(ev('seeker-agent-1', 'user-1', 'casual_member', tick,
        'view_task_list', 'On dashboard — scanning existing tasks',
        BEHAVIOR_OUTCOMES.SUCCESS, '3 tasks visible', 'tasks/dashboard', null));

      // Intentional gap: try to create task with empty title
      recorder.record(ev('seeker-agent-1', 'user-1', 'casual_member', tick,
        'attempt_create_task_empty_title', 'Testing whether empty title is validated',
        BEHAVIOR_OUTCOMES.ERROR_422, 'No validation error shown — empty title accepted silently',
        'tasks/dashboard', null));
      recorder.record(ev('seeker-agent-1', 'user-1', 'casual_member', tick,
        'create_task_with_title', 'Creating task with valid title after gap discovery',
        BEHAVIOR_OUTCOMES.SUCCESS, 'Task "Review PR #42" created', 'tasks/dashboard',
        JSON.stringify({ user_id: 'user-1' })));

      // Task detail flow
      recorder.record(ev('seeker-agent-1', 'user-1', 'casual_member', tick,
        'click_task_item', 'Drilling into task-2 to complete it',
        BEHAVIOR_OUTCOMES.SUCCESS, 'Navigated to task/task-2', 'tasks/dashboard',
        JSON.stringify({ task_id: 'task-2' })));
      recorder.record(ev('seeker-agent-1', 'user-1', 'casual_member', tick,
        'complete_task', 'Marking task-2 as completed',
        BEHAVIOR_OUTCOMES.SUCCESS, 'task-2 status → completed', 'tasks/task-detail',
        JSON.stringify({ task_id: 'task-2', user_id: 'user-1' })));

      // ── seeker-2: login → view dashboard ──────────────────────────────────
      if (tick === 1) {
        recorder.record(ev('seeker-agent-2', 'user-2', 'power_user', tick,
          'navigate_to_login', 'Second seeker starting session',
          BEHAVIOR_OUTCOMES.SUCCESS, null, 'auth/login', null));
        recorder.record(ev('seeker-agent-2', 'user-2', 'power_user', tick,
          'submit_login_form', 'Authenticating as user2@demo.test',
          BEHAVIOR_OUTCOMES.SUCCESS, null, 'auth/login',
          JSON.stringify({ user_id: 'user-2' })));
        recorder.record(ev('seeker-agent-2', 'user-2', 'power_user', tick,
          'view_task_list', 'Checking tasks assigned to me',
          BEHAVIOR_OUTCOMES.SUCCESS, 'Saw task-3 assigned to user-2', 'tasks/dashboard',
          JSON.stringify({ task_id: 'task-3' })));

        // ── employer-1: login → dashboard ───────────────────────────────────
        recorder.record(ev('employer-agent-1', 'emp-1', 'employer_manager', tick,
          'navigate_to_login', 'Employer checking team task board',
          BEHAVIOR_OUTCOMES.SUCCESS, null, 'auth/login', null));
        recorder.record(ev('employer-agent-1', 'emp-1', 'employer_manager', tick,
          'submit_login_form', 'Authenticating as employer1@demo.test',
          BEHAVIOR_OUTCOMES.SUCCESS, null, 'auth/login',
          JSON.stringify({ user_id: 'emp-1' })));
        recorder.record(ev('employer-agent-1', 'emp-1', 'employer_manager', tick,
          'view_dashboard_as_employer', 'Reviewing task distribution across team members',
          BEHAVIOR_OUTCOMES.SUCCESS, '3 tasks visible: 1 completed, 2 pending', 'tasks/dashboard',
          JSON.stringify({ user1_id: 'user-1', user2_id: 'user-2', task1_id: 'task-1', task2_id: 'task-2', task3_id: 'task-3' })));
      }

      // Profile view (tick 2+)
      if (tick === 2) {
        recorder.record(ev('seeker-agent-1', 'user-1', 'casual_member', tick,
          'navigate_to_profile', 'Checking completion stats',
          BEHAVIOR_OUTCOMES.SUCCESS, null, 'user/profile',
          JSON.stringify({ user_id: 'user-1' })));
        recorder.record(ev('seeker-agent-1', 'user-1', 'casual_member', tick,
          'logout', 'Session complete — signing out',
          BEHAVIOR_OUTCOMES.SUCCESS, null, 'user/profile',
          JSON.stringify({ user_id: 'user-1' })));
      }
    }

    recorder.flush();

    // Query the DB for the actual persisted count — catches any silent idempotency drops
    const countDb = new BetterSqlite3(dbPath);
    const { cnt } = countDb.prepare(
      'SELECT COUNT(*) as cnt FROM behavior_events WHERE simulation_id = ?'
    ).get(simulationId) as { cnt: number };
    countDb.close();

    console.log(`[demo] simulation: ${options.ticks} ticks, ${cnt} behavior events persisted`);
    return { simulationId, ticksCompleted: options.ticks, behaviorEventsWritten: cnt };
  }

  async exportEntities(iterRoot: string, entities: SeededEntity[]): Promise<void> {
    const dbPath = path.join(iterRoot, '.lisa_memory', 'lisa.db');

    // ── Extract candidate flows from behavior events ─────────────────────────
    const db = new BetterSqlite3(dbPath);
    let simulationId = 'demo';
    let flows: Array<{ screen: string; actions: string[]; errorCount: number }> = [];
    try {
      const simRow = db.prepare('SELECT simulation_id FROM behavior_events ORDER BY recorded_at ASC LIMIT 1').get() as any;
      if (simRow) simulationId = simRow.simulation_id;

      // Group events by screen_path
      const rows = db.prepare(`
        SELECT screen_path, action, outcome, COUNT(*) as cnt
        FROM behavior_events
        WHERE screen_path IS NOT NULL
        GROUP BY screen_path, action, outcome
        ORDER BY screen_path, cnt DESC
      `).all() as Array<{ screen_path: string; action: string; outcome: string; cnt: number }>;

      const screenMap = new Map<string, { actions: string[]; errorCount: number }>();
      for (const row of rows) {
        if (!screenMap.has(row.screen_path)) screenMap.set(row.screen_path, { actions: [], errorCount: 0 });
        const entry = screenMap.get(row.screen_path)!;
        entry.actions.push(row.action);
        if (row.outcome.startsWith('error')) entry.errorCount++;
      }
      flows = Array.from(screenMap.entries()).map(([screen, data]) => ({ screen, ...data }));
    } finally {
      db.close();
    }

    console.log(`[demo] exportEntities: extracted ${flows.length} candidate flows from ${simulationId}`);

    // ── Write candidate_flows.yaml ────────────────────────────────────────────
    const candidateFlowsPath = path.join(iterRoot, 'candidate_flows.yaml');
    const yaml = [
      `# candidate_flows.yaml — extracted from simulation ${simulationId}`,
      `# Generated: ${new Date().toISOString()}`,
      `# Entities: ${entities.map(e => e.alias).join(', ')}`,
      ``,
      ...flows.map(f => [
        `- screen: "${f.screen}"`,
        `  actions:`,
        ...f.actions.map(a => `    - "${a}"`),
        `  error_rate: ${f.errorCount > 0 ? (f.errorCount / f.actions.length).toFixed(2) : '0.00'}`,
        `  gap_detected: ${f.errorCount > 0}`,
      ].join('\n')),
    ].join('\n');
    fs.writeFileSync(candidateFlowsPath, yaml, 'utf8');

    // ── Discover data keys (try lisa-mcp, fall back to static map) ───────────
    const discoveredKeys = await this.discoverDataKeys(iterRoot);

    // ── Write generated Playwright specs ─────────────────────────────────────
    const specsDir = path.join(iterRoot, 'generated-flows');
    fs.mkdirSync(specsDir, { recursive: true });

    // 1. login_happy_path.spec.ts — should PASS
    fs.writeFileSync(path.join(specsDir, 'login_happy_path.spec.ts'), generateLoginSpec(discoveredKeys));

    // 2. task_completion_flow.spec.ts — should PASS
    fs.writeFileSync(path.join(specsDir, 'task_completion_flow.spec.ts'), generateTaskCompletionSpec(discoveredKeys));

    // 3. task_creation_validation.spec.ts — intentionally FAILS (gap: no validation message)
    fs.writeFileSync(path.join(specsDir, 'task_creation_validation.spec.ts'), generateTaskValidationSpec(discoveredKeys));

    console.log(`[demo] exportEntities: 3 generated specs written to ${specsDir}`);
    console.log(`[demo] exportEntities: data keys source — ${discoveredKeys.source}`);
    console.log(`[demo]   discovered screens: ${Object.keys(discoveredKeys.keys).join(', ')}`);
    console.log(`[demo]   gap: task_creation_validation.spec.ts will fail — no validation message rendered`);
  }

  async clean(_iterRoot: string): Promise<void> {}

  private async discoverDataKeys(iterRoot: string): Promise<{ source: string; keys: Record<string, string[]> }> {
    try {
      const lisaPackage = '@kaneshir/lisa-mcp';
      const { buildLisaMcpCommand, verifyBinary } = await import(lisaPackage) as LisaMcpModule;
      const verify = await verifyBinary();
      if (!verify.ok) throw new Error(verify.error ?? 'binary not ready');

      const { cmd, args } = buildLisaMcpCommand();
      const discovered = await runLisaMcpExploration(cmd, args, iterRoot);
      if (discovered) {
        return { source: `lisa-mcp ${verify.version}`, keys: discovered };
      }
    } catch (err) {
      console.log(`[demo] lisa-mcp unavailable (${(err as Error).message}) — using static key map`);
    }
    return { source: 'static-key-map', keys: DATA_KEY_MAP };
  }
}

// ---------------------------------------------------------------------------
// Lisa MCP exploration — JSON-RPC 2.0 over stdio
// ---------------------------------------------------------------------------
async function runLisaMcpExploration(
  cmd: string, args: string[], iterRoot: string,
): Promise<Record<string, string[]> | null> {
  const appDir = path.resolve(__dirname, 'app');
  const lisaMemoryDir = path.join(iterRoot, '.lisa_memory');

  return new Promise((resolve) => {
    const timeout = setTimeout(() => { proc.kill(); resolve(null); }, 15_000);
    const proc = spawn(cmd, args, {
      env: { ...process.env, LISA_MEMORY_DIR: lisaMemoryDir },
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    let buf = '';
    const pending = new Map<number, (r: any) => void>();
    let nextId = 1;

    proc.stdout.on('data', (chunk: Buffer) => {
      buf += chunk.toString();
      const lines = buf.split('\n');
      buf = lines.pop() ?? '';
      for (const line of lines) {
        if (!line.trim()) continue;
        try {
          const msg = JSON.parse(line);
          if (msg.id != null && pending.has(msg.id)) {
            pending.get(msg.id)!(msg);
            pending.delete(msg.id);
          }
        } catch {
          continue;
        }
      }
    });

    proc.on('error', () => { clearTimeout(timeout); resolve(null); });
    proc.on('close', () => { clearTimeout(timeout); });

    const send = (obj: object) => {
      proc.stdin.write(JSON.stringify(obj) + '\n');
    };

    const call = (method: string, params: object): Promise<any> => {
      return new Promise((res) => {
        const id = nextId++;
        pending.set(id, res);
        send({ jsonrpc: '2.0', id, method, params });
      });
    };

    const run = async () => {
      try {
        // Initialize
        await call('initialize', {
          protocolVersion: '2024-11-05',
          capabilities: {},
          clientInfo: { name: 'stf-demo', version: '1.0.0' },
        });
        send({ jsonrpc: '2.0', method: 'notifications/initialized', params: {} });

        const discovered: Record<string, string[]> = {};

        // Navigate to each screen and explore
        const screens: Array<{ hash: string; name: string }> = [
          { hash: 'home', name: 'home' },
          { hash: 'login', name: 'login' },
          { hash: 'dashboard', name: 'dashboard' },
          { hash: 'profile', name: 'profile' },
        ];

        for (const screen of screens) {
          const navResult = await call('tools/call', {
            name: 'lisa_navigate',
            arguments: { url: `file://${appDir}/index.html#${screen.hash}` },
          });
          if (navResult?.error) continue;

          const exploreResult = await call('tools/call', {
            name: 'lisa_explore_screen',
            arguments: {},
          });
          const text = exploreResult?.result?.content?.[0]?.text ?? '';
          // Parse data-key values from explore output
          const keyMatches = [...text.matchAll(/data-key[:\s"']+([a-z0-9_.{}-]+)/gi)];
          if (keyMatches.length > 0) {
            discovered[screen.name] = [...new Set(keyMatches.map(m => m[1]))];
          } else {
            discovered[screen.name] = DATA_KEY_MAP[screen.name as keyof typeof DATA_KEY_MAP] ?? [];
          }
        }

        proc.kill();
        clearTimeout(timeout);
        resolve(Object.keys(discovered).length > 0 ? discovered : null);
      } catch {
        proc.kill();
        clearTimeout(timeout);
        resolve(null);
      }
    };

    run();
  });
}

// ---------------------------------------------------------------------------
// Generated spec templates
// ---------------------------------------------------------------------------
function generateLoginSpec(_keys: { source: string; keys: Record<string, string[]> }): string {
  return `/**
 * login_happy_path.spec.ts
 * AUTO-GENERATED by synthetic-test-fabric demo (source: ${_keys.source})
 * Candidate flow: auth/login → tasks/dashboard
 */
import { test, expect } from '@playwright/test';

test('login happy path: valid credentials → dashboard', async ({ page }) => {
  await page.goto('index.html#login');
  await expect(page.locator('[data-key="login.title"]')).toBeVisible();
  await page.locator('[data-key="login.email_input"]').fill('user1@demo.test');
  await page.locator('[data-key="login.password_input"]').fill('demo123');
  await page.locator('[data-key="login.submit_btn"]').click();
  await expect(page.locator('[data-key="dashboard.title"]')).toBeVisible();
  await expect(page.locator('[data-key="dashboard.task_list"]')).toBeVisible();
});

test('login: invalid credentials show error', async ({ page }) => {
  await page.goto('index.html#login');
  await page.locator('[data-key="login.email_input"]').fill('bad@example.com');
  await page.locator('[data-key="login.password_input"]').fill('wrong');
  await page.locator('[data-key="login.submit_btn"]').click();
  await expect(page.locator('[data-key="login.error_msg"]')).toBeVisible();
  await expect(page.locator('[data-key="login.error_msg"]')).toContainText('Invalid');
});
`;
}

function generateTaskCompletionSpec(_keys: { source: string; keys: Record<string, string[]> }): string {
  return `/**
 * task_completion_flow.spec.ts
 * AUTO-GENERATED by synthetic-test-fabric demo (source: ${_keys.source})
 * Candidate flow: tasks/dashboard → tasks/task-detail → complete
 */
import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('index.html#login');
  await page.locator('[data-key="login.email_input"]').fill('user1@demo.test');
  await page.locator('[data-key="login.password_input"]').fill('demo123');
  await page.locator('[data-key="login.submit_btn"]').click();
  await expect(page.locator('[data-key="dashboard.title"]')).toBeVisible();
});

test('complete a pending task via task detail', async ({ page }) => {
  // Click second task item (index 1 = task-2, which is pending)
  await page.locator('[data-testid="task-item"]:nth-child(2)').click();
  await expect(page.locator('[data-key="task.title_heading"]')).toBeVisible();
  await expect(page.locator('[data-key="task.complete_btn"]')).toBeVisible();
  await page.locator('[data-key="task.complete_btn"]').click();
  await expect(page.locator('[data-key="task.reopen_btn"]')).toBeVisible();
  await expect(page.locator('[data-key="task.status_value"]')).toHaveText('completed');
});

test('reopen a completed task', async ({ page }) => {
  // Click first task (task-1 = already completed in default data)
  await page.locator('[data-testid="task-item"]:nth-child(1)').click();
  await expect(page.locator('[data-key="task.reopen_btn"]')).toBeVisible();
  await page.locator('[data-key="task.reopen_btn"]').click();
  await expect(page.locator('[data-key="task.complete_btn"]')).toBeVisible();
  await expect(page.locator('[data-key="task.status_value"]')).toHaveText('pending');
});

test('back button returns to dashboard', async ({ page }) => {
  await page.locator('[data-testid="task-item"]').first().click();
  await page.locator('[data-key="task.back_btn"]').click();
  await expect(page.locator('[data-key="dashboard.title"]')).toBeVisible();
});
`;
}

function generateTaskValidationSpec(_keys: { source: string; keys: Record<string, string[]> }): string {
  return `/**
 * task_creation_validation.spec.ts
 * AUTO-GENERATED by synthetic-test-fabric demo (source: ${_keys.source})
 *
 * GAP PROBE: simulation agent discovered that submitting an empty task title
 * produces no visible validation error. This spec probes whether the UI
 * correctly rejects empty submissions and shows dashboard.validation_error.
 *
 * Expected: FAIL — this gap exists in the current implementation.
 * The score will record discovery_yield += 1 for each new gap found.
 */
import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('index.html#login');
  await page.locator('[data-key="login.email_input"]').fill('user1@demo.test');
  await page.locator('[data-key="login.password_input"]').fill('demo123');
  await page.locator('[data-key="login.submit_btn"]').click();
  await expect(page.locator('[data-key="dashboard.title"]')).toBeVisible();
});

test('GAP: empty task title should show validation error [EXPECTED FAIL]', async ({ page }) => {
  // Leave title input empty and click create
  await page.locator('[data-key="dashboard.task_title_input"]').clear();
  await page.locator('[data-key="dashboard.create_task_btn"]').click();
  // This assertion will FAIL — the app accepts empty titles silently
  await expect(page.locator('[data-key="dashboard.validation_error"]')).toBeVisible();
});

test('GAP: empty task title should NOT appear in task list [EXPECTED FAIL]', async ({ page }) => {
  const initialCount = await page.locator('[data-testid="task-item"]').count();
  await page.locator('[data-key="dashboard.task_title_input"]').clear();
  await page.locator('[data-key="dashboard.create_task_btn"]').click();
  // This assertion will FAIL — the empty task IS added to the list
  await expect(page.locator('[data-testid="task-item"]')).toHaveCount(initialCount);
});
`;
}

// ---------------------------------------------------------------------------
// BrowserAdapter — routes on project param
// ---------------------------------------------------------------------------
export class DemoBrowserAdapter implements BrowserAdapter {
  constructor(private readonly demoRoot: string) {}

  async runSpecs(options: { iterRoot: string; project: string; allowFailures: boolean }): Promise<BrowserRunResult> {
    if (options.project === 'generate-flows') {
      // GENERATE_FLOWS phase: specs already written in exportEntities — nothing to do
      console.log('[demo] browser: generate-flows — specs already generated in exportEntities');
      return { passed: 0, failed: 0, total: 0, resultsPath: '' };
    }

    if (options.project === 'generated-flows') {
      return this.runGeneratedFlows(options.iterRoot, options.allowFailures);
    }

    // Default: regression (static navigation.spec.ts)
    return this.runRegression(options.iterRoot, options.allowFailures);
  }

  private runRegression(iterRoot: string, allowFailures: boolean): BrowserRunResult {
    const resultsPath = path.join(iterRoot, 'flow-results.json');
    const configPath = path.join(this.demoRoot, 'playwright.config.ts');
    const appDir = path.join(this.demoRoot, 'app');
    const cmd = `npx playwright test --config=${configPath} --reporter=json`;
    const env = { ...process.env, PLAYWRIGHT_JSON_OUTPUT_NAME: resultsPath, DEMO_APP_DIR: appDir };
    try {
      execSync(cmd, { cwd: this.demoRoot, env, stdio: 'inherit' });
    } catch {
      if (!allowFailures) throw new Error('[demo] Regression Playwright flows failed');
    }
    return { passed: 0, failed: 0, total: 0, resultsPath };
  }

  private runGeneratedFlows(iterRoot: string, allowFailures: boolean): BrowserRunResult {
    const specsDir = path.join(iterRoot, 'generated-flows');
    if (!fs.existsSync(specsDir)) {
      console.log('[demo] browser: no generated-flows dir found — skipping generated flows');
      return { passed: 0, failed: 0, total: 0, resultsPath: '' };
    }
    const resultsPath = path.join(iterRoot, 'generated-flow-results.json');
    const configPath = path.join(this.demoRoot, 'generated-playwright.config.ts');
    const appDir = path.join(this.demoRoot, 'app');
    const cmd = `npx playwright test --config=${configPath} --reporter=json`;
    const existingNodePath = process.env.NODE_PATH ?? '';
    const packageNodeModules = path.resolve(this.demoRoot, '..', 'node_modules');
    const env = {
      ...process.env,
      PLAYWRIGHT_JSON_OUTPUT_NAME: resultsPath,
      GENERATED_FLOWS_DIR: specsDir,
      DEMO_APP_DIR: appDir,
      NODE_PATH: existingNodePath ? `${packageNodeModules}:${existingNodePath}` : packageNodeModules,
    };
    try {
      execSync(cmd, { cwd: this.demoRoot, env, stdio: 'inherit' });
    } catch {
      if (!allowFailures) throw new Error('[demo] Generated Playwright flows failed');
    }
    return { passed: 0, failed: 0, total: 0, resultsPath };
  }
}

// ---------------------------------------------------------------------------
// ScoringAdapter — real dimension computation
// ---------------------------------------------------------------------------
export class DemoScoringAdapter implements ScoringAdapter {
  async score(iterRoot: string): Promise<FabricScore> {
    const regressionResults = this.parseResults(path.join(iterRoot, 'flow-results.json'));
    const generatedResults = this.parseResults(path.join(iterRoot, 'generated-flow-results.json'));
    const coverageDelta = this.computeCoverageDelta(iterRoot);

    const regTotal = regressionResults.total;
    const regPassed = regressionResults.passed;
    const genTotal = generatedResults.total;
    const genPassed = generatedResults.passed;
    const genFailed = generatedResults.failed;

    // discovery_yield: generated flow failures that represent real gaps
    const discoveryYield = genFailed > 0 ? Math.min(10, genFailed * 3) : 0;

    // flow_coverage: combined pass rate across regression AND generated flows
    // Intentional gap-probe failures in generated specs honestly deflate this score,
    // showing that not all user journeys are working correctly.
    const combinedTotal = regTotal + genTotal;
    const combinedPassed = regPassed + genPassed;
    const flowCoverage = combinedTotal > 0 ? Math.round((combinedPassed / combinedTotal) * 10) : 5;

    // regression_health: 10 - penalty per regression failure
    const regressionHealth = regTotal > 0
      ? Math.max(0, 10 - (regressionResults.failed * 2))
      : 10;

    // fixture_health: were entities seeded and verified?
    const exportPath = path.join(iterRoot, 'mini-sim-export.json');
    const fixtureHealth = fs.existsSync(exportPath) ? 10 : 0;

    // persona_realism: based on behavior event diversity
    const dbPath = path.join(iterRoot, '.lisa_memory', 'lisa.db');
    const personaRealism = this.computePersonaRealism(dbPath);

    const overall = Math.round(
      (regressionHealth * 0.30 + flowCoverage * 0.25 + discoveryYield * 0.20 +
       personaRealism * 0.15 + fixtureHealth * 0.10) * 10
    ) / 10;

    const score: FabricScore = {
      simulationId: 'demo',
      generatedAt: new Date().toISOString(),
      overall,
      dimensions: {
        persona_realism: personaRealism,
        coverage_delta: coverageDelta,
        fixture_health: fixtureHealth,
        discovery_yield: discoveryYield,
        regression_health: regressionHealth,
        flow_coverage: flowCoverage,
      },
      details: {
        regression: { total: regTotal, passed: regPassed, failed: regressionResults.failed },
        generated: { total: genTotal, passed: genPassed, failed: genFailed },
      },
    };

    fs.writeFileSync(path.join(iterRoot, 'fabric-score.json'), JSON.stringify(score, null, 2));
    return score;
  }

  private parseResults(filePath: string): { total: number; passed: number; failed: number } {
    if (!fs.existsSync(filePath)) return { total: 0, passed: 0, failed: 0 };
    try {
      const results = JSON.parse(fs.readFileSync(filePath, 'utf8'));
      let passed = 0; let failed = 0;
      const countSpecs = (suites: any[]) => {
        for (const s of suites ?? []) {
          for (const spec of s.specs ?? []) { spec.ok ? passed++ : failed++; }
          countSpecs(s.suites ?? []);
        }
      };
      countSpecs(results.suites ?? []);
      return { total: passed + failed, passed, failed };
    } catch { return { total: 0, passed: 0, failed: 0 }; }
  }

  private computeCoverageDelta(iterRoot: string): number {
    // Derive previous iter root from naming convention (iter-002 → iter-001)
    const iterName = path.basename(iterRoot);
    const match = iterName.match(/^iter-(\d+)$/);
    if (!match) return 0;
    const prevNum = parseInt(match[1], 10) - 1;
    if (prevNum < 1) return 0;
    const prevIterRoot = path.join(path.dirname(iterRoot), `iter-${String(prevNum).padStart(3, '0')}`);
    if (!fs.existsSync(prevIterRoot)) return 0;

    const curr = this.parseResults(path.join(iterRoot, 'flow-results.json'));
    const prev = this.parseResults(path.join(prevIterRoot, 'flow-results.json'));
    if (prev.total === 0) return 0;

    const prevRate = prev.passed / prev.total;
    const currRate = curr.total > 0 ? curr.passed / curr.total : 0;
    return Math.max(0, Math.min(10, Math.round((currRate - prevRate) * 100)));
  }

  private computePersonaRealism(dbPath: string): number {
    if (!fs.existsSync(dbPath)) return 5;
    try {
      const db = new BetterSqlite3(dbPath);
      const row = db.prepare(`
        SELECT
          COUNT(DISTINCT agent_id) as agent_count,
          COUNT(DISTINCT screen_path) as screen_count,
          COUNT(DISTINCT entity_id) as entity_count,
          COUNT(*) as total_events
        FROM behavior_events
      `).get() as any;
      db.close();
      if (!row || row.total_events === 0) return 5;
      // Score based on diversity: more agents, more screens = more realistic
      const agentScore = Math.min(3, row.agent_count);
      const screenScore = Math.min(4, row.screen_count);
      const entityScore = Math.min(3, row.entity_count);
      return agentScore + screenScore + entityScore;
    } catch { return 5; }
  }
}

// ---------------------------------------------------------------------------
// FeedbackAdapter
// ---------------------------------------------------------------------------
export class DemoFeedbackAdapter implements FeedbackAdapter {
  async feedback(iterRoot: string, options: {
    score: FabricScore;
    loopId: string;
    iteration: number;
    previousIterRoot: string | null;
  }): Promise<FabricFeedback> {
    const generatedResultsPath = path.join(iterRoot, 'generated-flow-results.json');
    let failedFlows: Array<import('../dist/index.js').PlaywrightFailedFlow & { suggested_scenario: string | null }> = [];

    if (fs.existsSync(generatedResultsPath)) {
      try {
        const parsed = parsePlaywrightResults(generatedResultsPath);
        failedFlows = parsed.failed_flows.map(f => ({ ...f, suggested_scenario: null }));
      } catch (err) {
        console.log(`[demo] unable to parse generated-flow-results.json (${(err as Error).message})`);
      }
    }

    const personaAdjustments: PersonaAdjustment[] = failedFlows.length > 0
      ? [{
          persona_id: 'casual_member',
          field: 'pressure.urgency',
          old_value: 'low',
          new_value: 'high',
          reason: `${failedFlows.length} gap${failedFlows.length === 1 ? '' : 's'} found in generated flows`,
        }]
      : [];

    const feedback: FabricFeedback = {
      schema_version: 1,
      loop_id: options.loopId,
      iteration: options.iteration,
      simulation_id: options.score.simulationId,
      previous_iteration_root: options.previousIterRoot,
      generated_specs: [],
      score_snapshot: options.score,
      failed_flows: failedFlows,
      persona_adjustments: personaAdjustments,
    };

    fs.writeFileSync(path.join(iterRoot, 'fabric-feedback.json'), JSON.stringify(feedback, null, 2));
    return feedback;
  }
}

// ---------------------------------------------------------------------------
// MemoryAdapter
// ---------------------------------------------------------------------------
export class DemoMemoryAdapter implements MemoryAdapter {
  migrate(_dbPath: string): void {}
  writeEvent(_dbPath: string, _event: RecorderInput): void {}
  resolveEntity(_dbPath: string, _alias: string): SeededEntity | null { return null; }
  listEntities(_dbPath: string, _simulationId: string): SeededEntity[] { return []; }
}

// ---------------------------------------------------------------------------
// Reporter — structured output
// ---------------------------------------------------------------------------
export class DemoReporter implements Reporter {
  async report(score: FabricScore, iterRoot: string): Promise<FabricReport> {
    const sep = '─'.repeat(52);
    console.log(`\n[demo] ┌─ Score Report ${'─'.repeat(38)}`);
    console.log(`[demo] │  Loop Root: ${path.dirname(iterRoot)}`);
    console.log(`[demo] │  Iteration: ${path.basename(iterRoot)}`);
    console.log(`[demo] ├${sep}`);
    console.log(`[demo] │  overall:           ${score.overall.toFixed(1)}/10`);
    console.log(`[demo] ├${sep}`);
    console.log(`[demo] │  regression_health: ${score.dimensions.regression_health}/10  (passing baseline tests)`);
    console.log(`[demo] │  flow_coverage:     ${score.dimensions.flow_coverage}/10  (regression pass rate)`);
    console.log(`[demo] │  discovery_yield:   ${score.dimensions.discovery_yield}/10  (gaps found by generated specs)`);
    console.log(`[demo] │  persona_realism:   ${score.dimensions.persona_realism}/10  (agent/screen/entity diversity)`);
    console.log(`[demo] │  fixture_health:    ${score.dimensions.fixture_health}/10  (entities seeded & verified)`);
    console.log(`[demo] │  coverage_delta:    ${score.dimensions.coverage_delta}/10  (improvement vs prev iteration)`);
    if (score.details) {
      console.log(`[demo] ├${sep}`);
      const r = (score.details as any).regression ?? {};
      const g = (score.details as any).generated ?? {};
      if (r.total) console.log(`[demo] │  regression:  ${r.passed}/${r.total} passed`);
      if (g.total)  console.log(`[demo] │  generated:   ${g.passed}/${g.total} passed  (${g.failed} gap${g.failed !== 1 ? 's' : ''} discovered)`);
    }
    console.log(`[demo] └${sep}`);
    return { format: 'console', content: '' };
  }
}

// ---------------------------------------------------------------------------
// ScenarioPlanner
// ---------------------------------------------------------------------------
export class DemoScenarioPlanner implements ScenarioPlanner {
  async plan(score: FabricScore, _iterRoot: string): Promise<ScenarioPlan> {
    const adjustments: PersonaAdjustment[] = [];
    if (score.dimensions.discovery_yield > 0) {
      adjustments.push({
        persona_id: 'casual_member',
        field: 'trade',
        old_value: 'exploratory',
        new_value: 'validation',
        reason: 'gaps discovered in previous iteration',
      });
    }
    if (score.dimensions.regression_health < 8) {
      adjustments.push({
        persona_id: 'casual_member',
        field: 'pressure.urgency',
        old_value: 'high',
        new_value: 'low',
        reason: 'regression health degraded',
      });
    }
    return {
      scenarioName: score.dimensions.discovery_yield > 0 ? 'gap_regression_probe' : 'baseline_demo_flow',
      rationale: `score=${score.overall.toFixed(1)}, discovery=${score.dimensions.discovery_yield}`,
      personaAdjustments: adjustments,
    };
  }
}
